### ISSUE TITLE
use-config-prompts is not a valid input option

### ISSUE THREAD

**Issue by nwaughachukwuma** [promptfoo/promptfoo-action#106]
> Warning: Unexpected input(s) 'use-config-prompts', valid inputs are ['github-token', 'prompts', 'config', 'cache-path', 'openai-api-key', 'promptfoo-version', 'no-share']

**Comment by typpo** [comment]
The release was not yet published. Please try again with `v1`

**Comment by nwaughachukwuma** [comment]
Ok, thanks
