### ISSUE TITLE
Runs with failed assertions don't get posted to comments

### ISSUE THREAD

**Issue by nwaughachukwuma** [promptfoo/promptfoo-action#111]
When a run has failed assertions, `promptfoo/actions` should post the output of that run as specified in the following image

<img src="https://private-user-images.githubusercontent.com/310310/248143799-ec75fb39-c6b1-4395-9e41-6d66a7bf8657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTQzOTcsIm5iZiI6MTcwODM1NDA5NywicGF0aCI6Ii8zMTAzMTAvMjQ4MTQzNzk5LWVjNzVmYjM5LWM2YjEtNDM5NS05ZTQxLTZkNjZhN2JmODY1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxNDQ4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmY5NWRmMGJlZTYzMDMwMWM0OTU2MWZlODkzYTFiYmUzMWJmN2FiNGQwM2MxN2YwYTcwNDEyM2NkYmVmNjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F5_m72Ql1nb1KtFCteHkAOVpbI1DF-GHfDOOSct2_zM" alt="Run with failed assertions" />

**Comment by typpo** [comment]
Thanks for the report! #112 should fix
