### ISSUE TITLE
Fail a job with failed assertion 

### ISSUE THREAD

**Issue by nwaughachukwuma** [promptfoo/promptfoo-action#114]
#112 fixes #111, but it's better to fail the job altogether or provide an option or flag for this.

> I think it's best to post the result of a failed run and still throw error (fail the CI job run)
>
> That way, we don't have a job run where there's a failed assertion and the CI passes.
>
> If it does not align with your philosophy is here, you should consider exposing a flag/option for this.

**Comment by typpo** [comment]
That definitely makes sense.  #116 should implement this behavior - the comment gets posted no matter what, but the exit status is failed when promptfoo returns a nonzero exit code.  Thanks for the suggestion @nwaughachukwuma
