### ISSUE TITLE
Bug?: promptfoo-action not doing anything

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo-action#86]
Check the config and logs in https://github.com/promptfoo/promptfoo-action/issues/85.

Basically, the action is integrated, but it's not actually running the eval.  Any ideas what the issue is?

I am thinking there is some way to exit `promptfoo-action` where nothing happens, and a warning isn't logged.  It would be good to warn for empty invocations

**Comment by typpo** [comment]
The underlying issue is fixed!
